### ISSUE TITLE
addRoute

### ISSUE THREAD

**Issue by Sessay** [zhoufanglu/dynamic-vue-router#1]
你好，我按照你的方式修改了代码，刷新后界面还是空白的

**Comment by zhoufanglu** [comment]
> 你好，我按照你的方式修改了代码，刷新后界面还是空白的

是否能提供代码，或者报错信息

**Comment by Sessay** [comment]
<img width="951" alt="WeChatc64bb904fe5b5ab8c167b911f02e0aeb" src="https://user-images.githubusercontent.com/29590568/142170343-99e8e081-489e-4b99-9f75-072e0c404c2f.png">
<img width="1230" alt="WeChat838df2cab9eb1590153f58968acd5e01" src="https://user-images.githubusercontent.com/29590568/142170388-38ccc1d2-d45d-4636-b9f2-2c87815e14e5.png">

**Comment by Sessay** [comment]
"vue": "^3.0.0" + "vue-router": "4"

**Comment by zhoufanglu** [comment]
> "vue": "^3.0.0" + "vue-router": "4"

`vuex-persistedstate`防丢失插件装了吗？

**Comment by Sessay** [comment]
有的

**Comment by zhoufanglu** [comment]
> 有的

vue3+vue-router4版本的还没试过，或者你能提供代码仓库吗？

**Comment by Sessay** [comment]
> > 有的
> 
> vue3+vue-router4版本的还没试过，或者你能提供代码仓库吗？
内部项目😂

**Comment by Sessay** [comment]
![image](https://user-images.githubusercontent.com/29590568/142191124-7a15d0f4-2a17-449d-aebe-621df6df2ea3.png)
我对比了一下，发现你的路由是写在路由文件里面的，我的是纯动态生成的，不知道是不是这个原因

**Comment by zhoufanglu** [comment]
router4有更新， 我重新写了一篇文章，你可以看[这里](https://juejin.cn/post/7043988643941203975)  
* 重置路由不需要了
* 动态引入有一些修改
* getRoutes也有点变化
其它没什么变化.
